print('このゲームは二人用です')
apple_price = int(input('答えを入力してください:'))

a = apple_price
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')
print('待て')

# 変数 money に数値 1000 を代入してください


input_count = input('適当に数字を入力してください：')
count = int(input_count)



# money と total_price の比較結果によって条件を分岐してください
if count == apple_price:
    print('正解です')
if count > apple_price:
    print('答えより大きいです')
    print('あと４回')
elif count < apple_price:
    print('答えより小さいです')
    print('あと４回')


if count != apple_price:
    input_count_2 = int(input('適当に数字を入力してください：'))
    if input_count_2 == apple_price:
        print('正解です')
    if input_count_2 > apple_price:
        print('答えより大きいです')
        print('あと３回')
    elif input_count_2 < apple_price:
        print('答えより小さいです')
        print('あと３回')

if input_count_2 != apple_price:
    input_count_3 = int(input('適当に数字を入力してください：'))
    if input_count_3 == apple_price:
        print('正解です')
    if input_count_3 > apple_price:
        print('答えより大きいです')
        print('あと２回')
    elif input_count_3 < apple_price:
        print('答えより小さいです')
        print('あと２回')

if input_count_3 != apple_price:
    input_count_4 = int(input('適当に数字を入力してください：'))
    if input_count_4 == apple_price:
        print('正解です')
    if input_count_4 > apple_price:
        print('答えより大きいです')
        print('あと一回')
    elif input_count_4 < apple_price:
        print('答えより小さいです')
        print('あと一回')


if input_count_4 != apple_price:
    input_count_5 = int(input('適当に数字を入力してください：'))
    if input_count_5 == apple_price:
        print('正解です')
    if input_count_5 > apple_price:
        print('答えより大きいです')
        print('お前の負け')
    elif input_count_5 < apple_price:
        print('答えより小さいです')
        print('お前の負け')
